config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :employees
  resources :establishments
  resources :app_users


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/app_user.rb
class AppUser < ApplicationRecord
  enum user_type: { owner: 'owner', employee: 'employee', client: 'client' }

  # Adicione os atributos de endereço
  attribute :address, :string
  attribute :city, :string
  attribute :state, :string
  attribute :zipcode, :string
end

app/controllers/app_users_controller.rb
class AppUsersController < ApplicationController
  before_action :set_app_user, only: %i[ show edit update destroy ]

  # GET /app_users or /app_users.json
  def index
    @app_users = AppUser.all
  end

  # GET /app_users/1 or /app_users/1.json
  def show
  end

  # GET /app_users/new
  def new
    @app_user = AppUser.new
  end

  # GET /app_users/1/edit
  def edit
  end

  # POST /app_users or /app_users.json
  def create
    @app_user = AppUser.new(app_user_params)

    respond_to do |format|
      if @app_user.save
        format.html { redirect_to app_user_url(@app_user), notice: "App user was successfully created." }
        format.json { render :show, status: :created, location: @app_user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @app_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_users/1 or /app_users/1.json
  def update
    respond_to do |format|
      if @app_user.update(app_user_params)
        format.html { redirect_to app_user_url(@app_user), notice: "App user was successfully updated." }
        format.json { render :show, status: :ok, location: @app_user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @app_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_users/1 or /app_users/1.json
  def destroy
    @app_user.destroy

    respond_to do |format|
      format.html { redirect_to app_users_url, notice: "App user was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_user
      @app_user = AppUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def app_user_params
      params.fetch(:app_user, {})
    end
end

app/helpers/app_users_helper.rb
module AppUsersHelper
end

app/views/app_users/_app_user.html.erb
<div id="<%= dom_id app_user %>">
</div>

app/views/app_users/_form.html.erb
<%= form_with(model: app_user, class: "contents") do |form| %>
  <% if app_user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(app_user.errors.count, "error") %> prohibited this app_user from being saved:</h2>

      <ul>
        <% app_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/app_users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing app user</h1>

  <%= render "form", app_user: @app_user %>

  <%= link_to "Show this app user", @app_user, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to app users", app_users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/app_users/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "App users" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">App users</h1>
    <%= link_to "New app user", new_app_user_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="app_users" class="min-w-full">
    <% @app_users.each do |app_user| %>
      <%= render app_user %>
      <p>
        <%= link_to "Show this app user", app_user, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/app_users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New app user</h1>

  <%= render "form", app_user: @app_user %>

  <%= link_to "Back to app users", app_users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/app_users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @app_user %>

    <%= link_to "Edit this app user", edit_app_user_path(@app_user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to app users", app_users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this app user", @app_user, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>